"""updated assignment sub

Revision ID: 24cb1b90dd3c
Revises: caa5c5a6e75c
Create Date: 2025-05-06 02:05:14.122490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24cb1b90dd3c'
down_revision: Union[str, None] = 'caa5c5a6e75c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    '''op.drop_constraint(None, 'assignment_materials', type_='foreignkey')
    op.drop_constraint(None, 'assignment_materials', type_='foreignkey')
    op.create_foreign_key(None, 'assignment_materials', 'course_materials', ['material_id'], ['id'])
    op.create_foreign_key(None, 'assignment_materials', 'assignments', ['assignment_id'], ['id'])'''
    op.add_column('assignment_submissions', sa.Column('ai_evaluation_count', sa.Integer(), nullable=True))
    '''op.create_index(op.f('ix_studyguide_usages_course_id'), 'studyguide_usages', ['course_id'], unique=False)
    op.create_index(op.f('ix_studyguide_usages_id'), 'studyguide_usages', ['id'], unique=False)
    op.create_index(op.f('ix_studyguide_usages_student_id'), 'studyguide_usages', ['student_id'], unique=False)'''
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    """op.drop_index(op.f('ix_studyguide_usages_student_id'), table_name='studyguide_usages')
    op.drop_index(op.f('ix_studyguide_usages_id'), table_name='studyguide_usages')
    op.drop_index(op.f('ix_studyguide_usages_course_id'), table_name='studyguide_usages')"""
    op.drop_column('assignment_submissions', 'ai_evaluation_count')
    """op.drop_constraint(None, 'assignment_materials', type_='foreignkey')
    op.drop_constraint(None, 'assignment_materials', type_='foreignkey')
    op.create_foreign_key(None, 'assignment_materials', 'assignments', ['assignment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'assignment_materials', 'course_materials', ['material_id'], ['id'], ondelete='CASCADE')"""
    # ### end Alembic commands ###
