"""added module and difficulty to quiz

Revision ID: 2cc3068bf752
Revises: daa1929d9c54
Create Date: 2025-06-18 20:52:14.265278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc3068bf752'
down_revision: Union[str, None] = 'daa1929d9c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('quizzes', sa.Column('module_id', sa.Integer(), nullable=True))
    #op.add_column('quizzes', sa.Column('difficulty', sa.String(), nullable=False, server_default='medium'))
    #op.create_index(op.f('ix_quizzes_module_id'), 'quizzes', ['module_id'], unique=False)
    #op.create_foreign_key(None, 'quizzes', 'course_modules', ['module_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'quizzes', type_='foreignkey')
    #op.drop_index(op.f('ix_quizzes_module_id'), table_name='quizzes')
    #op.drop_column('quizzes', 'difficulty')
    #op.drop_column('quizzes', 'module_id')
    # ### end Alembic commands ###
