"""Add new fields to Course model

Revision ID: 3b4938cce949
Revises: f0f482a4183d
Create Date: 2025-06-08 22:08:38.793199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4938cce949'
down_revision: Union[str, None] = 'f0f482a4183d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    

    
    # Add new columns to courses table


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes

    
    # Revert description column using batch mode
    
    # ### end Alembic commands ###