"""changed table name

Revision ID: 67c60af8f722
Revises: 84245254d5bf
Create Date: 2025-04-20 18:58:17.468651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67c60af8f722'
down_revision: Union[str, None] = '84245254d5bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_submissions', sa.Column('ai_score', sa.Integer(), nullable=True))
    op.add_column('assignment_submissions', sa.Column('teacher_score', sa.Integer(), nullable=True))
    op.drop_column('assignment_submissions', 'grade')
    op.drop_column('assignment_submissions', 'ai_feedback')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_submissions', sa.Column('ai_feedback', sa.TEXT(), nullable=True))
    op.add_column('assignment_submissions', sa.Column('grade', sa.VARCHAR(), nullable=True))
    op.drop_column('assignment_submissions', 'teacher_score')
    op.drop_column('assignment_submissions', 'ai_score')
    # ### end Alembic commands ###
