"""Add file_size column to CourseMaterial

Revision ID: 692081940f23
Revises: 3b4938cce949
Create Date: 2025-06-14 21:55:50.333671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692081940f23'
down_revision: Union[str, None] = '3b4938cce949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_materials', sa.Column('file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('course_materials', 'file_size')
    # ### end Alembic commands ###
