"""peer-quiz addition

Revision ID: 7ca061117206
Revises: 43c394186444
Create Date: 2025-06-27 07:00:58.343944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca061117206'
down_revision: Union[str, None] = '43c394186444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('creator_participation_id', sa.Integer(), nullable=True),
    sa.Column('solver_id', sa.Integer(), nullable=True),
    sa.Column('solver_group_id', sa.Integer(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['inclass_activities.id'], ),
    sa.ForeignKeyConstraint(['creator_participation_id'], ['activity_participations.id'], ),
    sa.ForeignKeyConstraint(['solver_group_id'], ['activity_groups.id'], ),
    sa.ForeignKeyConstraint(['solver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_id'), 'quiz_attempts', ['id'], unique=False)
    op.create_table('quiz_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_participation_id', sa.Integer(), nullable=True),
    sa.Column('commenter_id', sa.Integer(), nullable=True),
    sa.Column('commenter_group_id', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('comment_type', sa.String(length=50), nullable=True),
    sa.Column('question_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commenter_group_id'], ['activity_groups.id'], ),
    sa.ForeignKeyConstraint(['commenter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creator_participation_id'], ['activity_participations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_comments_id'), 'quiz_comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_comments_id'), table_name='quiz_comments')
    op.drop_table('quiz_comments')
    op.drop_index(op.f('ix_quiz_attempts_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    # ### end Alembic commands ###
