"""fixed foreign key issue

Revision ID: 85807f813a80
Revises: 2cc3068bf752
Create Date: 2025-06-18 21:11:55.485475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85807f813a80'
down_revision: Union[str, None] = '2cc3068bf752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_quizzes_module_id_course_modules",
        "quizzes", "course_modules",
        ["module_id"], ["id"],
        ondelete="SET NULL"
    )
    op.create_foreign_key(
        "fk_quizzes_course_id_courses",
        "quizzes", "courses",
        ["course_id"], ["id"],
        ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_constraint("fk_quizzes_module_id_course_modules", "quizzes", type_="foreignkey")
    op.drop_constraint("fk_quizzes_course_id_courses", "quizzes", type_="foreignkey")
    # ### end Alembic commands ###
