"""Added quiz quota

Revision ID: adab82765aa3
Revises: 7bc08a254c16
Create Date: 2025-05-03 20:40:28.077389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adab82765aa3'
down_revision: Union[str, None] = '7bc08a254c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'assignment_materials', type_='foreignkey')
    #op.drop_constraint(None, 'assignment_materials', type_='foreignkey')
    #op.create_foreign_key(None, 'assignment_materials', 'course_materials', ['material_id'], ['id'])
    #op.create_foreign_key(None, 'assignment_materials', 'assignments', ['assignment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'assignment_materials', type_='foreignkey')
    #op.drop_constraint(None, 'assignment_materials', type_='foreignkey')
    #op.create_foreign_key(None, 'assignment_materials', 'assignments', ['assignment_id'], ['id'], ondelete='CASCADE')
    #op.create_foreign_key(None, 'assignment_materials', 'course_materials', ['material_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
