"""module publish

Revision ID: ebe56990e26f
Revises: 684690eb3c7b
Create Date: 2025-06-22 04:04:55.588332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe56990e26f'
down_revision: Union[str, None] = '684690eb3c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_modules', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.add_column('course_submodules', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.add_column('quizzes', sa.Column('is_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('quizzes', 'is_published')

    op.drop_column('course_submodules', 'is_published')
    op.drop_column('course_modules', 'is_published')
    # ### end Alembic commands ###
